### ISSUE TITLE
How do I build this locally ?

### ISSUE THREAD

**Issue by ta1bbty** [PierreCapo/react-native-socials#2]
Hi @PierreCapo 

Thanks for this amazing library.
I want to use the twitter component in my react native app.
I am getting the tweet details from my backend and hence I don't want to provide `consumer secret` and `key` rather pass the tweet details as props.

However, I am facing difficulty compiling the lib locally.

This is what I am doing : 
`tsc --build tsconfig.json`

It gives `14 errors`. I am very new to typescript and node ecosystem in general. However I've some experience in JS.
```sh
❯ tsc --build tsconfig.json
src/Instagram/index.tsx:41:25 - error TS2349: This expression is not callable.
  No constituent of type 'ViewStyle | TextStyle | ImageStyle' is callable.

41     <View style={styles.container(containerBorderRadius)}>
                           ~~~~~~~~~

src/Instagram/index.tsx:45:11 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ImageProps>): Image', gave the following error.
    Type 'ViewStyle | TextStyle | ImageStyle' is not assignable to type 'StyleProp<ImageStyle>'.
      Type 'ViewStyle' is not assignable to type 'StyleProp<ImageStyle>'.
        Type 'ViewStyle' is not assignable to type 'ImageStyle'.
          Types of property 'overflow' are incompatible.
            Type '"hidden" | "visible" | "scroll" | undefined' is not assignable to type '"hidden" | "visible" | undefined'.
              Type '"scroll"' is not assignable to type '"hidden" | "visible" | undefined'.
  Overload 2 of 2, '(props: ImageProps, context?: any): Image', gave the following error.
    Type 'ViewStyle | TextStyle | ImageStyle' is not assignable to type 'StyleProp<ImageStyle>'.
      Type 'ViewStyle' is not assignable to type 'StyleProp<ImageStyle>'.
        Type 'ViewStyle' is not assignable to type 'ImageStyle'.

45           style={styles.profilePicture}
             ~~~~~

  node_modules/@types/react-native/index.d.ts:3804:5
    3804     style?: StyleProp<ImageStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>'
  node_modules/@types/react-native/index.d.ts:3804:5
    3804     style?: StyleProp<ImageStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>'

src/Instagram/index.tsx:51:13 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ImageProps>): Image', gave the following error.
    Type 'ViewStyle | TextStyle | ImageStyle' is not assignable to type 'StyleProp<ImageStyle>'.
      Type 'ViewStyle' is not assignable to type 'StyleProp<ImageStyle>'.
        Type 'ViewStyle' is not assignable to type 'ImageStyle'.
  Overload 2 of 2, '(props: ImageProps, context?: any): Image', gave the following error.
    Type 'ViewStyle | TextStyle | ImageStyle' is not assignable to type 'StyleProp<ImageStyle>'.
      Type 'ViewStyle' is not assignable to type 'StyleProp<ImageStyle>'.
        Type 'ViewStyle' is not assignable to type 'ImageStyle'.

51             style={styles.verified}
               ~~~~~

  node_modules/@types/react-native/index.d.ts:3804:5
    3804     style?: StyleProp<ImageStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>'
  node_modules/@types/react-native/index.d.ts:3804:5
    3804     style?: StyleProp<ImageStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>'

src/Instagram/index.tsx:80:31 - error TS2349: This expression is not callable.
  No constituent of type 'ViewStyle | TextStyle | ImageStyle' is callable.

80                 style={styles.postImage(
                                 ~~~~~~~~~

src/Twitter/TwitterText.tsx:84:7 - error TS2322: Type '(string | Element)[]' is not assignable to type 'string[]'.
  Type 'string | Element' is not assignable to type 'string'.
    Type 'Element' is not assignable to type 'string'.

84       transformedText = transformTextToAddColors(
         ~~~~~~~~~~~~~~~

src/Twitter/TwitterText.tsx:93:5 - error TS2322: Type '(string | Element)[]' is not assignable to type 'string[]'.

93     transformedText = transformTextToAddColors(
       ~~~~~~~~~~~~~~~

src/Twitter/TwitterText.tsx:103:5 - error TS2322: Type '(string | Element)[]' is not assignable to type 'string[]'.

103     transformedText = transformTextToAddColors(
        ~~~~~~~~~~~~~~~

src/Twitter/TwitterText.tsx:113:5 - error TS2322: Type '(string | Element)[]' is not assignable to type 'string[]'.

113     transformedText = transformTextToAddColors(
        ~~~~~~~~~~~~~~~

src/Twitter/index.tsx:64:27 - error TS2349: This expression is not callable.
  No constituent of type 'ViewStyle | TextStyle | ImageStyle' is callable.

64       <View style={styles.container(containerBorderRadius)}>
                             ~~~~~~~~~

src/Twitter/index.tsx:88:35 - error TS2349: This expression is not callable.
  No constituent of type 'ViewStyle | TextStyle | ImageStyle' is callable.

88               <View style={styles.embedContainer(cornerRadius)}>
                                     ~~~~~~~~~~~~~~

src/Twitter/index.tsx:96:35 - error TS2349: This expression is not callable.
  No constituent of type 'ViewStyle | TextStyle | ImageStyle' is callable.

96               <View style={styles.embedContainer(cornerRadius)}>
                                     ~~~~~~~~~~~~~~

src/Twitter/index.tsx:100:35 - error TS2349: This expression is not callable.
  No constituent of type 'ViewStyle | TextStyle | ImageStyle' is callable.

100               <View style={styles.embedContainer(cornerRadius)}>
                                      ~~~~~~~~~~~~~~

src/Twitter/index.tsx:109:35 - error TS2349: This expression is not callable.
  No constituent of type 'ViewStyle | TextStyle | ImageStyle' is callable.

109               <View style={styles.embedContainer(cornerRadius)}>
                                      ~~~~~~~~~~~~~~

src/Twitter/index.tsx:144:17 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ImageProps>): Image', gave the following error.
    Type 'ViewStyle | TextStyle | ImageStyle' is not assignable to type 'StyleProp<ImageStyle>'.
      Type 'ViewStyle' is not assignable to type 'StyleProp<ImageStyle>'.
        Type 'ViewStyle' is not assignable to type 'ImageStyle'.
  Overload 2 of 2, '(props: ImageProps, context?: any): Image', gave the following error.
    Type 'ViewStyle | TextStyle | ImageStyle' is not assignable to type 'StyleProp<ImageStyle>'.
      Type 'ViewStyle' is not assignable to type 'StyleProp<ImageStyle>'.
        Type 'ViewStyle' is not assignable to type 'ImageStyle'.

144                 style={styles.heart}
                    ~~~~~

  node_modules/@types/react-native/index.d.ts:3804:5
    3804     style?: StyleProp<ImageStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>'
  node_modules/@types/react-native/index.d.ts:3804:5
    3804     style?: StyleProp<ImageStyle>;
             ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>'


Found 14 errors.
```

Can you point me in the right direction as to what should I be looking into here :sweat_smile: 

Thanks again.

**Comment by ta1bbty** [comment]
Do I have to build with some specific options or something else ?

P.S. It already took me sometime to figure out that to compile i had to run `tsc --build tsconfig.json`

It built one time, not sure how did that happen :sweat_smile:

**Comment by PierreCapo** [comment]
Hello @ta1bbty

In order to run the project for development purpose you need to (run those command from the root folder) :

1. Set up the example app :  `cd example && yarn`
2. Optional (if you work on iOS): `cd example && pod install`
3. Run the app : `yarn start`

I can have a look at your use case though, if I have some times in the next hours/days, I'll try to have a look and make an api in the components for that.

**Comment by PierreCapo** [comment]
Ok, forget about what I said, it's indeed pretty broken. I'm investigating it now

**Comment by PierreCapo** [comment]
It should work better now, just need to copy images from the Instagram and Twitter folder to the ones in the dist folder.

By the way, I've just done a release to use custom Twitter data in the component with the prop `useCustomTweetExtendedData`. If the data which comes from your backend is exactly the one with the `?tweet_mode=extended ` attribute, it should do the trick

**Comment by ta1bbty** [comment]
Thanks a lot @PierreCapo , I was about to make a workaround for this.
I want to add some customization to the way tweets are displayed for which I need to change the source and compile it again.
Like adding some text below the tweet that's being displayed.

For now I am directly changing the source of locally installed package.
If you can tell me how you compile the package ( to push the new release on npm registry ), that would be a ton of help.

**Comment by ta1bbty** [comment]
Also @PierreCapo 
I think the PR broke the click to open tweet functionality.
That's now when I click on the tweet it doesn't open the actual tweet. Only the hashtag works fine and not the tweets or the profile id.

**Comment by PierreCapo** [comment]
@ta1bbty I'll have a look, but I'm not sure the pr broke the link stuff since I really didn't touch this part of the code. But let's see, I'll look at it later.

> If you can tell me how you compile the package ( to push the new release on npm registry ), that would be a ton of help.
If I understand your question, if you want to publish your package on npm, you need to rename the library in the package.json, create an account on npm, and then follow a tutorial how to publish it.

Note, that if you want to use it for your internal work only, you can just make a fork on Github and add a line like this in your package.json :
```
    "react-native-socials": "ta1bbty/react-native-socials#19d14e94",
```
Iirc, it will detect it needs to pull the package from Github automatically and not from npm
if `19d14e94` is the commit hash on Github you want to rely on.

**Comment by ta1bbty** [comment]
Hi @PierreCapo 
Thanks for the detailed instructions. I followed that to the dot. You can check the commit [here](https://github.com/ta1bbty/react-native-socials/commit/4baeb358356487e8345353e24e5e5c8e3068322a).

**npm** pulls it correctly but since it isn't compiled so I am getting raw `.tsx` files in my `node_modules` folder.
![image](https://user-images.githubusercontent.com/45117337/90986917-36805a00-e5a4-11ea-9461-c2239cfa3917.png)

Can you guide on some instructions as to how I can compile this or so resolve this ?

Sorry to bother again :/

**Comment by PierreCapo** [comment]
Sorry if I wasn't clear, the package.json change is for when you want to use the code you did as a package (because you asked how to publish it on npm).

In the development environment, you don't need to do that. Instead:
1. Fork the whole code base like you did.
2. And follow the steps mentionned in : https://github.com/PierreCapo/react-native-socials/issues/2#issuecomment-674981721

I've made a little video about how to compile and set up the project. It's missing the command `react-native run-ios ` in the `example` folder but otherwise it should be ok : https://gofile.io/d/4EJHu7

**Comment by ta1bbty** [comment]
Hi @PierreCapo 
Thanks a lot, that did help.
Thanks for making the video, that was more than expected :innocent:
Great work :tada: 
Closing this issue now :)

**Comment by PierreCapo** [comment]
Happy it helped you, good luck in your dev 😀
