### ISSUE TITLE
Issue displaying video component with expo

### ISSUE THREAD

**Issue by ta1bbty** [PierreCapo/react-native-socials#3]
Hi @PierreCapo 

Once again thanks for the great package.
I am using this with expo and was having some issues with the video component in twitter video ( probably would same go with instagram ).

The workaround I found was to replace this with the `expo-av` package's `Video` component, like this.

![image](https://user-images.githubusercontent.com/45117337/90639884-f429e680-e24c-11ea-95b5-caf785c040df.png)

Currently this is the solution I am considering but as I am pretty new to this ecosystem I would love to get your suggestions here.

Thanks :slightly_smiling_face:

**Comment by PierreCapo** [comment]
Hello @ta1bbty indeed, the video component this library is using is hardcoded and it is `react-native-video` which is not compatible with expo.
What you are doing is the right path, you should use `expo-av` and plug the props properly

Ideally, this `react-native-socials` should let consumers pick whatever video library they want easily and not rely on `react-native-video`

**Comment by ta1bbty** [comment]
@PierreCapo thanks.
So, closing this for now. If you ever work on making the package video agnostic, please tag me there :)
