### ISSUE TITLE
On click of twitter card doesn't open the tweet

### ISSUE THREAD

**Issue by ta1bbty** [PierreCapo/react-native-socials#4]
Hi @PierreCapo 
First of all thanks, this is quite a nice work and extremely helpful for me.
I tried creating a tweet card , all works good but if I click on the tweet card it should open the tweet.
This works fine when passing in consumer key and getting tweet that way.

But it **doesn't** work when passing tweet as json ( offline ) .

Thanks.

**Comment by PierreCapo** [comment]
Hello @ta1bbty .
Thanks for the kind words. Seems like your problem has been solved by #6 being merged and released in 0.0.23
Have a good day!
